Add a second solution for python challenges.
viebel/data-oriented-programming pull request #14
Opened 2022-01-25 21:45 UTC by Konfuzian

2022-01-26 04:33 UTC, viebel requested changes
Nice!

2022-01-26 04:33 UTC, viebel commented on challenges/python-2/challenges.py
> +from toolz.dicttoolz import assoc_in
Why do you need both `pydash` and `toolz.dicttoolz`?

2022-01-26 04:33 UTC, viebel commented on challenges/python-2/challenges.py
> +	return {key_map.get(k, k): v for k, v in data.items()}
Nice!

2022-01-26 04:33 UTC, viebel commented on challenges/python-2/challenges.py
> +	return {**d1 , **d2}
Are you sure it does a deep merge?

2022-01-26 11:29 UTC, Konfuzian commented on challenges/python-2/challenges.py
> +from toolz.dicttoolz import assoc_in
I need `assoc_in` from `toolz` because `set` in pydash modifies the object in place, and I couldn't find another method that just creates an updated object.

2022-01-26 11:30 UTC, Konfuzian commented on challenges/python-2/challenges.py
> +	return {**d1 , **d2}
No not sure... I need to check that.

2022-01-26 11:31 UTC, Konfuzian commented on challenges/python-2/challenges.py
> +	return {key_map.get(k, k): v for k, v in data.items()}
Thanks! I got inspiration from the other python challenge solution here.

2022-01-26 12:16 UTC, Konfuzian commented on challenges/python-2/challenges.py
> +	return {**d1 , **d2}
Alright, I found a library that does a deep merge for me. I like libraries.

2022-01-26 13:48 UTC, viebel commented on challenges/python-2/challenges.py
> +from toolz.dicttoolz import assoc_in
Could you use only `toolz` and get rid of `pydash`?

2022-01-26 18:27 UTC, Konfuzian commented on challenges/python-2/challenges.py
> +from toolz.dicttoolz import assoc_in
Yes, I've updated the branch. I just had to use `get_in` instead of `get` and swap the order of the object and path arguments.

2022-01-27 04:28 UTC, viebel commented on challenges/python-2/challenges.py
> +from toolz.dicttoolz import assoc_in
Perfect!

2022-01-27 04:28 UTC, merged